#!/bin/zsh

# better ls
alias ls="ls --color -F"
alias ll="ls -lh"

# dots
alias dots="dotfiles"

# quick clear
alias x="clear"

# git aliases
alias ga="git add"
alias gb="git branch"
alias gc="git commit"
alias gco="git checkout"
alias gd="git diff"
alias gds="git diff --staged"
alias gg="git push"
alias ggf="git push --force-with-lease"
alias gl="git lg"
alias gn="git checkout -b"
alias gp="git pull"
alias gr="git reset HEAD --"
alias grb="git rebase -i"
alias grbc="git rebase --continue"
alias grbs="git rebase --skip"
alias gs="git status"

# npm aliases
alias ni="npm install"
alias nid="npm install --save-dev"
alias nu="npm uninstall"
alias ns="npm start"
alias nt="npm test"
alias nr="npm run"
alias nb="npm run build"
alias nd="npm run dev"

# python aliases
alias p="python3"
alias python="python3"
alias pip="pip3"

# rust aliases
alias r="rustup"
alias c="cargo"

# suffixed aliases
alias -s js="node"
alias -s ts="typescript"
alias -s py="python3"
alias -s git="git clone"

# bulk association
alias -s {md,json,css,html}=code

# misc
alias zrc="source $HOME/.zshrc"

# macOS aliases
if [[ $OSTYPE == darwin* ]]; then
  # restart
  alias ugh="osascript -e 'tell app \"System Events\" to restart'"

  # sleep
  alias z="pmset displaysleepnow"
  alias zz="pmset sleepnow"

  # flush dns cache
  alias flushdns='dscacheutil -flushcache'
fi
