#!/bin/zsh

# shell ux
alias hist="history 1"

# ls
alias ls="ls -F --color"
alias lsa="ls -a"
alias ll="ls -lh"
alias lla="ls -lha"
alias l=ll

# nvim or else
alias v="$EDITOR"
alias vi="$EDITOR"
alias vim="$EDITOR"
alias nvim="$EDITOR"

# tmux
alias tmux="tmux -2 -f '$XDG_CONFIG_HOME/tmux/tmux.conf'"
alias tmuxa='tmux attach || tmux new-session'

# vim-style quit
alias :q="exit"

# overrides
alias cat="bat"
alias top="btop"

# fzf with preview
alias ff="fzf --preview 'bat --color=always --style=numbers --line-range=:500 {}'"

# dotfiles
alias dots="dotfiles"

# git aliases
alias ga="git add"
alias gb="git branch"
alias gc="git commit"
alias gco="git checkout"
alias gcp="git cherry-pick"
alias gd="git diff"
alias gds="git diff --staged"
alias gg="git push"
alias ggf="git push --force-with-lease"
alias gl="git lg"
alias gn="git checkout -b"
alias gp="git pull"
alias gr="git reset HEAD --"
alias grb="git rebase -i"
alias grbc="git rebase --continue"
alias grbs="git rebase --skip"
alias gs="git status"

# npm aliases
alias ni="npm install"
alias nid="npm install --save-dev"
alias nu="npm uninstall"
alias ns="npm start"
alias nt="npm test"
alias nr="npm run"
alias nb="npm run build"
alias nd="npm run dev"
alias nx="npx nx"

# k8s aliases
alias kgp="kubectl get pod"
alias kdp="kubectl delete pod"
alias k8logs="kubectl logs -f"
k8clean() {
	kubectl delete pod $(kubectl get pods | awk '/Evicted|ImagePullBackOff|Completed|CrashLoopBackOff|Error|OOMKilled|ContainerStatusUnknown/ {print $1}')
}
k8exec() {
	kubectl exec --stdin --tty $1 -- /bin/sh
}
k8context() {
	kubectl config get-contexts -o name | grep $1 --color='never' | xargs kubectl config use-context
}

# python aliases
alias p="python3"
alias python="python3"
alias pip="pip3"

# suffixed aliases
alias -s js="node"
alias -s ts="deno run"
alias -s py="python3"
alias -s git="git clone"

# bulk association
alias -s {md,json,css,html}=nvim

# misc
alias zrc="source $HOME/.zshrc"

# macOS aliases
if [[ $(uname) == "Darwin" ]]; then
	# use the GNU coreutils ls if available
	gls -d . &>/dev/null 2>&1 && alias ls="gls -F --color" || alias ls="ls -FG"

	# flush dns cache
	alias flushdns="dscacheutil -flushcache"

	# get ip address
	alias ip="ipconfig getifaddr en0"

	# force removal of quarantine attribute on unsigned executables
	alias allow-run="xattr -d com.apple.quarantine"

	# flush dns cache
	alias flushdns="dscacheutil -flushcache"

	# force removal of quarantine attribute on unsigned executables
	alias allow-run="xattr -d com.apple.quarantine"
fi
