#!/bin/zsh

plugins=(
  '/opt/homebrew/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh'
)

for plugin in $plugins; do [[ -f $plugin ]] && source $plugin; done

if [[ -v ZSH_HIGHLIGHT_STYLES ]]; then
  # disable underline
  ZSH_HIGHLIGHT_STYLES[path]=none
  ZSH_HIGHLIGHT_STYLES[path_prefix]=none

  # disable bold
  ZSH_HIGHLIGHT_STYLES[arg0]=fg=green,normal
  ZSH_HIGHLIGHT_STYLES[unknown-token]=fg=red,normal
fi
