#!/bin/zsh

case $(uname) in
	Darwin)
		ZSH_PLUGINS_DIR="$(brew --prefix)/share"
		;;
	Linux)
		ZSH_PLUGINS_DIR="/usr/share"
		;;
esac

ZSH_PLUGINS=(
	"$ZSH_PLUGINS_DIR/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh"
)

for plugin in $ZSH_PLUGINS; do
	[[ -f $plugin ]] && source $plugin;
done

if [[ -v ZSH_HIGHLIGHT_STYLES ]]; then
	# disable underline
	ZSH_HIGHLIGHT_STYLES[path]=fg=white,none
	ZSH_HIGHLIGHT_STYLES[path_prefix]=fg=white,none
fi
